name: review_repository
description: Dart package which manages the review domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  appcheap_flutter_core:
    path: ../../appcheap_flutter_core
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.0