name: store_setting_repository
description: Dart package which manages the store setting domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  appcheap_flutter_core:
    path: ../../appcheap_flutter_core

  formz: ^0.4.1
  # A Flutter plugin that provides a Google Maps widget.
  google_maps_flutter: ^2.1.3
  google_maps_flutter_web: ^0.3.2+1

  google_place_repository:
    path: ../google_place_repository

  json_annotation: ^4.4.0
  json_serializable: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.0